### ISSUE TITLE
Images are send, but just as a Link

### ISSUE THREAD

**Issue by Echolon** [anurodhp/Monal#131]
Hi,

today current Monal version (blabber.im) send a picture to Conversations (mailbox.org). I just received a simple link. No picture shown inline. I had to open the link. I know Conversations actually can show pictures inline.

Is this intended?

Cheers

**Comment by anurodhp** [comment]
I am in the process of switching to the oob tag that conversations uses. Ill double check to make sure its working right.

**Comment by Echolon** [comment]
Okay thanks. Blabber.im from conversations to conversations works fine. just to exclude server specific things

**Comment by anurodhp** [comment]
fix should apply to iOS too

**Comment by RandomBloke85** [comment]
Hello,

it seems, that in 2026 on the latest version this problem still persists. When sending an attachement from Monal to Android (Conversations, Monocle), the Android client just receives a notification with "image offered for download" and in the chat "Check image size". Since this is the same from Siskin, it might be an iOS thing, but maybe this is a known issue.

**Comment by licaon-kter** [comment]
Conversations (and itsf ork monocles) will autodownload files in private groups and 1:1 chats only, not in public channels.

How did you setup files autodownload? The received files are smaller than the limit?

Note that this issue is about receiving as links, you don't see that  issue if you see the check size button.

**Comment by RandomBloke85** [comment]
The issue is in 1:1 chats, fingerprints verified.
Autodownload is unlimited in unmetered connections and way below the limit in unmetered ones
Yes, technically you're correct. I'm not receiving links. But it was the closest to the check size button.
Anyway, don't understand where this is coming from. Maybe Prosody. Since it only occurs from messages from Monal, I thought the issue might be related to Monal.

**Comment by tmolitor-stud-tu** [comment]
@RandomBloke85 is this in Alpha or Stable/Beta?

It may also be that you enabled the DNSSEC check in the settings and that prevents (auto)download to work.
