### ISSUE TITLE
SCRAM-SHA-1(-PLUS) + SCRAM-SHA-256(-PLUS) supports

### ISSUE THREAD

**Issue by Neustradamus** [anurodhp/Monal#161]
"When using the SASL SCRAM mechanism, the SCRAM-SHA-256-PLUS variant SHOULD be preferred over the SCRAM-SHA-256 variant, and SHA-256 variants [RFC7677] SHOULD be preferred over SHA-1 variants [RFC5802]".

SCRAM-SHA-1(-PLUS):
- https://tools.ietf.org/html/rfc5802
- https://tools.ietf.org/html/rfc6120

SCRAM-SHA-256(-PLUS):
- https://tools.ietf.org/html/rfc7677 since 2015-11-02
- https://tools.ietf.org/html/rfc8600 since 2019-06-21: https://mailarchive.ietf.org/arch/msg/ietf-announce/suJMmeMhuAOmGn_PJYgX5Vm8lNA

I add SCRAM-SHA-512(-PLUS): https://xmpp.org/extensions/inbox/hash-recommendations.html

Linked to:
- https://github.com/scram-xmpp/info/issues/1

**Comment by licaon-kter** [comment]
What's [SHA-1](#37)? :-|

**Comment by tmolitor-stud-tu** [comment]
Those PLUS variants can not be implemented for TLS 1.3 due to a missing channel binding RFC for TLS 1.3. For the moment it does not seem that there will be any shortterm change here.

As we all are transitioning to TLS 1.3, this issue can be closed.
Feel free to reopen it, if the RFC situation changes here.

**Comment by Echolon** [comment]
Ok, I will close for the moment

**Comment by Neustradamus** [comment]
But TLS 1.2 is not removed ;)
Please reopen it.

**Comment by tmolitor-stud-tu** [comment]
@Neustradamus Adding a feature only supported in an old version of TLS is nothing we will do, for SCRAM-SHA-XXX thee is another issue still open: https://github.com/anurodhp/Monal/issues/37

**Comment by Neustradamus** [comment]
XMPP servers remove the old history unsecured MD5 support, any news on it?

**Comment by Neustradamus** [comment]
@anurodhp, @tmolitor-stud-tu: Can you reopen?
- https://tools.ietf.org/html/draft-whited-tls-channel-bindings-for-tls13-02

**Comment by Neustradamus** [comment]
@anurodhp, @tmolitor-stud-tu: Can you reopen?
- https://tools.ietf.org/html/draft-whited-tls-channel-bindings-for-tls13

-PLUS variants are important

Linked to:
- https://github.com/anurodhp/Monal/issues/37
- https://github.com/anurodhp/Monal/issues/384

**Comment by tmolitor-stud-tu** [comment]
I think it's way more important to have working MUC support and other bugfixes 
than having an additional layer against man-in-the-middle attacks.

You don't use TLS channel binding on your online banking website, too (in fact 
no website or browser supports channel binding).
Just plain old TLS with proper certificate checking.

Using a proper TLS certificate on the server should be sufficient.
Monal does proper certificate checking, too, if you don't disable it in 
advanced settings.

**Comment by Neustradamus** [comment]
SCRAM-SHA-512(-PLUS):
- https://tools.ietf.org/html/draft-melnikov-scram-sha-512

SCRAM-SHA3-512(-PLUS):
- https://tools.ietf.org/html/draft-melnikov-scram-sha3-512

**Comment by Neustradamus** [comment]
@ all: It is official for TLS 1.3 Binding!
- RFC 9266: Channel Bindings for TLS 1.3: https://tools.ietf.org/html/rfc9266

Details:
- tls-unique for TLS =< 1.2 (RFC5929)
- tls-server-end-point =< 1.2 + 1.3 (RFC5929)
- tls-exporter for TLS = 1.3 (RFC9266)

**Comment by tmolitor-stud-tu** [comment]
Yes, BUT: I don't know any method to get the required channel binding data on iOS. Until someone points me to some documentation, I can't implement this.

**Comment by Neustradamus** [comment]
@tmolitor-stud-tu: Where it must be added?
The goal is to inform Apple about missing parts.

**Comment by tmolitor-stud-tu** [comment]
Apple's Network Framewok (https://developer.apple.com/documentation/network?language=objc) needs a way to access the needed data. I don't know of any, but maybe I missed something.

**Comment by tmolitor-stud-tu** [comment]
We obviously have another serious protocol flow problem here, even if we manage to get the right value from Apple's Network Framework:

if we use that new channel binding, we can't be sure the server supports it already. That means if we use it, the server can respond with a `SASL failure` (containing some non standardized text describing the issue further).

We can not distinguish this `SASL failure` from an invalid username.
That means we have two options now: retry without channel-binding or fail the login.

Failing the login is obviously really bad UX , because the user can't use Monal to log in to her server anymore.

Retrying the login without channel-binding opens Monal up to a MITM downgrade attack. The attacker just has to fail the initial SASL authentication by changing the channel binding name in the initial SCRAM message to some random string and wait until Monal retries without channel binding.
