### ISSUE TITLE
Debugging the "There was a SASL error on the server" message?

### ISSUE THREAD

**Issue by jeffreyrack** [anurodhp/Monal#188]
The Monal app is no longer working on my Iphone when connecting to a server that previously worked.

When trying to connect to the server, I receive the message "There was a SASL error on the server", but when trying to connect to the server using other XMPP clients such as converse.js, I'm able to connect to the server, so it doesn't appear to be an issue with the server.

Is there a way I can receive more detailed debug information to help diagnose the issue?

I've tried changing the "Old Style TLS" flag, but the error is received with the flag both On and Off.

Thanks for creating this app, and any help you can provide here.

**Comment by anurodhp** [comment]
Hi grab the latest iOS beta here
https://testflight.apple.com/join/RjIlyvqa

Just follow the instructions to install it directly on your phone.  See if the issue is already fixed. If it isn't, on the betas, under settings at the bottom there is a log. This will show you every log message printed out on your phone.  There should be an error message printed somewhere there. If you can send that to me I can probably fix it quickly.  That message in particular is generated when there is a problem with the authentication and the server doesnt return a more descriptive message.

**Comment by jeffreyrack** [comment]
The latest beta build fixed this issue.
