### ISSUE TITLE
Add support for SplitScreen and Slide-Over on recent iPads

### ISSUE THREAD

**Issue by Shirk** [anurodhp/Monal#23]
Hi,
please consider adopting the [multitasking enhancements](https://developer.apple.com/library/prerelease/ios/documentation/WindowsViews/Conceptual/AdoptingMultitaskingOniPad/QuickStartForSlideOverAndSplitView.html#//apple_ref/doc/uid/TP40015145-CH13-SW1) introduced in iOS9.
Being able to work in split screen mode and having Monal always at hand would be **awesome**.
According to Apples documentation it shouldn't require any big changes and it would definitely make Monal stand out.

P.S. If you'd consider including the feature but don't find the time let me know - I could probably offer a PR

**Comment by anurodhp** [comment]
I've wanted to do this since it was announced. The way it works, with split view as the root controller means that it will only work on iOS 8 and up. This is why I'm dropping support for 6-7. 

There are also some structural changes that need to be made to accompany this, the tabbar needs to move to the master view etc. it's high in my list too because it makes sense to have an I'm client on the side .

**Comment by anurodhp** [comment]
This is in the current betas.
