### ISSUE TITLE
Otr

### ISSUE THREAD

**Issue by chazdiezal** [anurodhp/Monal#28]
Is otr support on the roadmap?

**Comment by anurodhp** [comment]
yes, i need to sort out how the gpl license will work on iOS

**Comment by therob84** [comment]
Since OTR is beeing kind of out-dated in mobile sector.....what's about OMEMO / Axolotl (libsalamander...)..., to beeing compatieble with [Conversations](http://conversations.im/) on Android?

Same discussion also here for ChatSecure: https://github.com/ChatSecure/ChatSecure-iOS/issues/376#issuecomment-182015533

**Comment by anurodhp** [comment]
closing since it seems we are all moving to a newer standard.
