### ISSUE TITLE
Monal not reliable at all

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [anurodhp/Monal#290]
Monal has plenty of bugs and Version 4.0 actually made matters worse, not better:
- Some messages do not arrive at all (even if the app is manually opened)
- Messages arrive late (together with following messages)

Not having the basic functionality of **reliable messaging** makes Monal completely unusable.
I can never be sure if a message actually arrived at all and always have to use other means of communication to verify/communicate reliably.

A messenger not delivering this most basic usage scenario is pure crap. Having a dark theme does not help at all and is a pure waste of time that should be better invested into making message delivery reliable.

_**That should be top priority before everything else!**_

**Comment by anurodhp** [comment]
Correct. This is what I have been working on for the past month.

**Comment by tmolitor-stud-tu** [comment]
No, a bunch of bugs were already present pre ios13 (like the bugs when fetching mam) and those are still not solved (see our chat history for details or some of my issues here on github).

I also tried to contact you via xmpp to help you iron these out (the old bugs **_and_** the new ones), but either all my messages did not arrive on your device(s) or you ignored me.

**Comment by Echolon** [comment]
Hey @tmolitor-stud-tu ,

everyone is very angry about the XMPP situation on iOS. It used to be the same for ChatSecure. I personally share your anger and see that this is exhausting for all of us who listen to our friends everyday "The app doesn't work"....

But as long as we can only rely on voluntary work, what options do we have as to wait for improvements? I already created an issue about rearranging with the "road map" #254. Furthermore, it's seems to be a hardcore issue as those problems occure for many xmpp app unfortunately. I'm not happy with the situation, but I think blameing any volunatry developer is not a solution. Also I am quite sure he doesn't ignore your informations but likely the messages ironically failed because of Monal. Have you check his other IDs he has? 
And last but not least, I think Anu really tried to get things going with iOS13 but ran into other issues. As many people update their phones not the worst approach I think.

I suggest we shouldn't go into fighting each other now. But I aggree, focus is important within 'our' limited resources.

Have a good night and still looking forward @anurodhp

**Comment by anurodhp** [comment]
It’s not arriving. The push issue is hard to diagnose because it seems to work and then it gets throttled and the app is closed. It’s also has chnaged in different os releases. I’m going to go with my plan b (a new messge alert) because Sometimes I’m not getting my own messages :(

**Comment by anurodhp** [comment]
addressed at least so people see there's a new message in 4.1. Working to restore the previews. 
https://github.com/anurodhp/Monal/issues/295
