### ISSUE TITLE
Lastest build can’t connect to open fire 4.5.1

### ISSUE THREAD

**Issue by ioscanner** [anurodhp/Monal#407]
It seems any version after build 4.6 (602) will not connect to open fire 4.5.1.  I have to roll back to version 4.6 (602) to register.  So something is breaking the auth process.

___________________________________
[ X] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for regarding labels https://github.com/anurodhp/Monal/labels

**Comment by licaon-kter** [comment]
Ping @guusdk

**Comment by guusdk** [comment]
This issue does not have much details to go on. Please provide more information.

**Comment by anurodhp** [comment]
There  is early beta code in monal 4.6 Playing around with the parser. It’s probably that.its being worked on

**Comment by tmolitor-stud-tu** [comment]
https://github.com/anurodhp/Monal/pull/404 should most probably fix it, at least it does for @FriedrichAltheide

**Comment by tmolitor-stud-tu** [comment]
@ioscanner can you check if beta 612 fixes your issue?

**Comment by ioscanner** [comment]
I will, but 612 has not posted to test flight yet.

**Comment by ioscanner** [comment]
Tested 614 and it works now, thanks!

**Comment by billroland** [comment]
I am having the same problem with Openfire but 614 does not work for me either.

**Comment by tmolitor-stud-tu** [comment]
@billroland could you give some more info? do you get a connection in openfire that gets dropped before monal is fully logged in? or do you get no connection at all? do you have SRV dns records configured for the domain you are trying to connect to?

**Comment by billroland** [comment]
The connection never appears in Openfire at all that I see.  Strangely enough though if I open the account and hit Advanced Settings and the server, I do see the list of XEP's the server supports.  I am getting push notifications from Openfire.  I do have SRV DNS records configured.

I do see this in Openfire when it tries to connect:
2020.05.13 12:57:33 org.jivesoftware.openfire.nio.ConnectionHandler - Closing connection due to error while processing message: <iq id='50-3001' type='result' to='im.fqdn.com/' ><query xmlns='http://jabber.org/protocol/disco#info' ><feature var='eu.siacs.conversations.axolotl.devicelist+notify' ></feature><feature var='http://jabber.org/protocol/caps' ></feature><feature var='http://jabber.org/protocol/disco#info' ></feature><feature var='http://jabber.org/protocol/disco#items' ></feature><feature var='http://jabber.org/protocol/muc' ></feature><feature var='urn:xmpp:jingle:1' ></feature><feature var='urn:xmpp:jingle:apps:rtp:1' ></feature><feature var='urn:xmpp:jingle:apps:rtp:audio' ></feature><feature var='urn:xmpp:jingle:transports:raw-udp:0' ></feature><feature var='urn:xmpp:jingle:transports:raw-udp:1' ></feature><feature var='urn:xmpp:receipts' ></feature><identity type='phone' category='client' name='Monal 4.6' ></identity></query></iq>
java.lang.IllegalArgumentException: Existing slash at the very end of the string indicates that an empty resource part is provided. This is illegal. Offending value: 'im.fqdn.com/'

**Comment by billroland** [comment]
```
2020.05.13 12:57:33 org.jivesoftware.openfire.nio.ConnectionHandler - Closing connection due to error while processing message: <iq id='50-3001' type='result' to='im.fqdn.com/' ><query xmlns='http://jabber.org/protocol/disco#info' ><feature var='eu.siacs.conversations.axolotl.devicelist+notify' ></feature><feature var='http://jabber.org/protocol/caps' ></feature><feature var='http://jabber.org/protocol/disco#info' ></feature><feature var='http://jabber.org/protocol/disco#items' ></feature><feature var='http://jabber.org/protocol/muc' ></feature><feature var='urn:xmpp:jingle:1' ></feature><feature var='urn:xmpp:jingle:apps:rtp:1' ></feature><feature var='urn:xmpp:jingle:apps:rtp:audio' ></feature><feature var='urn:xmpp:jingle:transports:raw-udp:0' ></feature><feature var='urn:xmpp:jingle:transports:raw-udp:1' ></feature><feature var='urn:xmpp:receipts' ></feature><identity type='phone' category='client' name='Monal 4.6' ></identity></query></iq>
java.lang.IllegalArgumentException: Existing slash at the very end of the string indicates that an empty resource part is provided. This is illegal. Offending value: 'im.fqdn.com/'
```

**Comment by guusdk** [comment]
Openfire performed a service discover request to Monal, which it answered. In the answer, the addressing seems to be misformed (that trailing slash should not appear). I'm thinking this is a small omission in service discovery handling in Monal.

**Comment by guusdk** [comment]
I'm unfamiliar with the code base (or even the language), but is there any chance that this evaluates to 'true' under certain conditions?

https://github.com/anurodhp/Monal/blob/develop/Monal/Classes/MLIQProcessor.m#L112

**Comment by anurodhp** [comment]
thats the bug, its  its cheking for nonnull which  includes an empty string. fixed.
