### ISSUE TITLE
HTTP File Upload: iOS uploads jpeg with png extension

### ISSUE THREAD

**Issue by SergiySW** [anurodhp/Monal#63]
Looking in code, at first iOS app converts any image to jpeg (UIImageJPEGRepresentation) and then uploads it as "photo.png" with "image/png" content-type. So, it always send jpeg file named "photo.png".
What is point of it?
I rather suggest convert photos and upload them as jpg with corrent content-type.
May be also replace filename "photo" with UUID 32 characters (as Conversations IM).

**Comment by StuartSeeley** [comment]
I'm seeing my uploaded jpgs being called photo.png too... 
Would be nice if the extension wasn't wrong...

**Comment by StuartSeeley** [comment]
Happens with XEP-0636 HTTP Upload as well as with Dropbox Integration upload.

**Comment by anurodhp** [comment]
yeah this and the other HTTP bug are placeholders I had put in that I forgot to fix .  fixing now.

**Comment by StuartSeeley** [comment]
Cool! Appreciate your efforts ... side note, not sure what’s going on but I’v been totally unable to sign in to my xmpp sever with Monal since last update... not sure why.  Sure I have people correct/etc.. didn’t change anything on server side and all the other xmpp apps can still sign on... miss Monal terribly.

Stuart

**Comment by anurodhp** [comment]
The last update was rough.  The change to the iOS SDK that came in iOS 10 messed stuff up that I have been doing since ios4. Hoping the current clean up will improve this a lot.
