### ISSUE TITLE
WIP: todo list

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [anurodhp/Monal#74]
This is a todo list (mainly for me) what should be improved in monal.

- Implement latest version of XEP-0313 (currently only mam:0 is implemented, mam:2 is current)
- [DONE, has to be tested, though] implement push (high priority)
- implement message receipts (XEP-0184)
- [DONE] fix id generation for IQ stanzas (currently multiple outgoing stanzas share the same id)
- create list of supported XEPs
- add support for MUC topics as display name

**Comment by WarrenBKN** [comment]
and xep-0384 ?

**Comment by tmolitor-stud-tu** [comment]
Sorry, progress in Monal is too slow.
I will concentrate on ChatSecure in the future.

ChatSecure already has OMEMO support btw. :)

**Comment by minus273** [comment]
Work happens in bursts as I have bandwidth. You've caught me at probably one of the worst times.

**Comment by anurodhp** [comment]
Work happens in bursts as I have bandwidth. You've caught me at probably one of the worst times.

**Comment by tmolitor-stud-tu** [comment]
Well I know. And that's ok, really.
But for me it was to slow as I needed a stable solution before I went on holiday with friends.
ChatSecure is now providing  a solution that's stable enough, so I switched over.

ChatSecure doesn't provide VoIP push right now, but I'll implement it once I have the time.
See https://github.com/ChatSecure/ChatSecure-iOS/issues/738 for a technical discussion on how we want to implement VoIP functionality in ChatSecure in order to be allowed to use VoIP push.

**Comment by LouDS** [comment]
Anurodhp, would  you be fixing Monal connections anytime soon?  Prior to installing v2.9.3 I was on v2.9.1 which worked without issues, I understand that the build for v2.9.2 had issues and the developer had to rebuild using iOS 9 SDK due to the VOIP socket being depreciated by apple. With version v2.9.3 I'm seeing very inconsistent results, some messages I send are not received when I reply to a conversation that someone else started. Perhaps there is still issues with background working. Is there a way for users to have access to version 2.9.1 until the instability is fixed?

One example of inconsistency is as follows:-
I get messages like for instance someone will ping me that I’ve not got an open window to in Monal or my desktop IM client, I see the first ping on Monal, but then the following pings do not show on the Monal app, I see the whole thread pop up on Pidgin, including the first Hi message that I saw on Monal, but the conversation then seems to cut off from Monal and only continue on the Pidgin client.

Regards
Louise

**Comment by maufl** [comment]
@tmolitor-stud-tu Come back @anurodhp is back at work again :D

**Comment by anurodhp** [comment]
@tmolitor-stud-tu I have a prosody server running that I am testing push on.  I made a change to the apps code to get it to work (see my fork).  It works when I post the token from the debugging POST endpoint. When it the message comes via xmpp, I see the following error any thoughts? monal.im and xmpp.monal.im are running on the same prosody server.  Would that be a problem? 

```
RECV(114): <message to='boston@monal.im'  id='5F710386-C71C-4EDD-B04C-F758F3F903BD'  type='chat' ><body>test</body></message>
Dec 12 09:52:38 c2s55e25e19dc80	debug	Handled 14 incoming stanzas
Dec 12 09:52:38 c2s55e25e19dc80	debug	Received[c2s]: <message id='5F710386-C71C-4EDD-B04C-F758F3F903BD' type='chat' to='boston@monal.im'>
Dec 12 09:52:38 c2s55e25e0bbec0	debug	Invoking cloud handle_notify_request() for smacks queued stanza
Dec 12 09:52:38 monal.im:cloud_notify	debug	Sending push notification for boston@monal.im to xmpp.monal.im (5044FDEC-32E4-41DE-8E6A-70EB33292DF0)
Dec 12 09:52:38 hostmanager	warn	Unhandled response sent to local host monal.im: <iq id='68ee59eadd7cfcd33301f0e85896b908e969483ceae7440893868c227025b1dd' type='error' to='monal.im' from='xmpp.monal.im'><error type='auth'><forbidden xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq>
```

**Comment by anurodhp** [comment]
scratch that. im an idiot. I was pointing to the wrong server.  @tmolitor-stud-tu  ill send a pull request for the things I have changed/added to your repo later.

**Comment by tmolitor-stud-tu** [comment]
glad to hear that it's working now :)

I guess I just forgot to add the util.hashes import...
