### ISSUE TITLE
need help/information fixing some smacks issues

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [anurodhp/Monal#79]
I can't reach you on xmpp anymore, so I'm using this ticket instead.

I'm currently fixing some bugs in the smacks implementation and stumbled upon some I can't fix:

1. When the app is opened (contact list) and it reconnects (using session resumption) a "reconnecting" toast is shown above the contact list. This toast isn't removed after successful connect and when the next reconnect is done, the toast is shown twice and so on.
2. When the session is resumed via smacks, the online status of all contacts is lost and they are shown as offline.

Could you point me in the right direction on how to solve this? Maybe some explanation on Monal's internals?

A third issue is this: I need a list of contacts inside xmpp.m. Where can I get this (`self.rosterList` is not always filled).

**Comment by tmolitor-stud-tu** [comment]
The online status of all contacts could also be queried by presence probes directly after a resume, if fixing the underlying bug is too difficult.

**Comment by tmolitor-stud-tu** [comment]
The exact text of the toast shown is "Logging in"...

**Comment by anurodhp** [comment]
I believe the roster list is deliberately not downloaded when it disconnects and reconnects. The specific reason for doing this is  the app was written for iOS 2 and there wasn't any backgrounding at the time. Every time you left the app it would disconnect and reconnect and the roster could be expensive on the slower devices from a decade ago. Later, i left it as is because i noticed it was the primary source for data and battery use when moving between cells and reconnecting.

**Comment by tmolitor-stud-tu** [comment]
Well...when using smacks the roster would not be loaded when you reconnect after moving between cells, so I think this is unneccessary now.

I removed the "don't download it on reconnect without smacks" part now.

**Comment by tmolitor-stud-tu** [comment]
See https://github.com/anurodhp/Monal/pull/80, I'm closing here :)
